[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.6",
    "streamlit>=1.41.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.6",
]
